name: Publish Docker Image and Notify

on:
  workflow_run:
    workflows: ["build-and-push"]
    types:
      - completed

jobs:
  publish-and-notify:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull shirishkc/grafana:latest

      - name: Send Discord notification on success
        if: ${{ needs.build-and-push.result == 'success' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "**[ SUCCESS ] Docker image shirishkc/grafana:latest published successfully to Docker Hub!**"

      - name: Send Discord notification on failure
        if: ${{ needs.build-and-push.result != 'success' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "**[ FAILURE ] Docker image shirishkc/grafana:latest failed to publish to Docker Hub!**"

  dummy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Job
        run: echo "This is a dummy job to satisfy the GitHub Actions requirement."
